# Generated by Django 3.1.7 on 2021-03-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('BAL', 'Baltimore Orioles'), ('TOR', 'Toronto Blue Jays'), ('LAD', 'Los Angeles Dodgers'), ('WAS', 'Washington Nationals'), ('CHW', 'Chicago White Sox'), ('MIA', 'Miami Marlins'), ('CLE', 'Cleveland Indians'), ('COL', 'Colorado Rockies'), ('LAA', 'Los Angeles Angels'), ('CHC', 'Chicago Cubs'), ('NYM', 'New York Mets'), ('AZ', 'Arizona Diamondbacks'), ('CIN', 'Cincinnati Reds'), ('MIL', 'Milwaukee Brewers'), ('SF', 'San Francisco Giants'), ('STL', 'St. Louis Cardinals'), ('NYY', 'New York Yankees'), ('HOU', 'Houston Astros'), ('TB', 'Tampa Bay Rays'), ('OAK', 'Oakland Athletics'), ('SEA', 'Seattle Mariners'), ('PIT', 'Pittsburgh Pirates'), ('MIN', 'Minnesota Twins'), ('DET', 'Detroit Tigers'), ('PHI', 'Philadelphia Phillies'), ('BOS', 'Boston Red Sox'), ('ATL', 'Atlanta Braves'), ('SD', 'San Diego Padres'), ('KC', 'Kansas City Royals'), ('TEX', 'Texas Rangers')], default='SD', max_length=254),
        ),
    ]
