# Generated by Django 3.1.7 on 2021-03-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('OAK', 'Oakland Athletics'), ('TEX', 'Texas Rangers'), ('STL', 'St. Louis Cardinals'), ('LAA', 'Los Angeles Angels'), ('SD', 'San Diego Padres'), ('MIL', 'Milwaukee Brewers'), ('CHC', 'Chicago Cubs'), ('NYY', 'New York Yankees'), ('HOU', 'Houston Astros'), ('PIT', 'Pittsburgh Pirates'), ('AZ', 'Arizona Diamondbacks'), ('COL', 'Colorado Rockies'), ('CLE', 'Cleveland Indians'), ('CIN', 'Cincinnati Reds'), ('MIA', 'Miami Marlins'), ('ATL', 'Atlanta Braves'), ('TOR', 'Toronto Blue Jays'), ('CHW', 'Chicago White Sox'), ('BAL', 'Baltimore Orioles'), ('SEA', 'Seattle Mariners'), ('PHI', 'Philadelphia Phillies'), ('TB', 'Tampa Bay Rays'), ('NYM', 'New York Mets'), ('BOS', 'Boston Red Sox'), ('DET', 'Detroit Tigers'), ('WAS', 'Washington Nationals'), ('MIN', 'Minnesota Twins'), ('LAD', 'Los Angeles Dodgers'), ('KC', 'Kansas City Royals'), ('SF', 'San Francisco Giants')], max_length=254),
        ),
    ]
