# Generated by Django 3.1.7 on 2021-03-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210317_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('WAS', 'Washington Nationals'), ('DET', 'Detroit Tigers'), ('SF', 'San Francisco Giants'), ('OAK', 'Oakland Athletics'), ('TB', 'Tampa Bay Rays'), ('MIN', 'Minnesota Twins'), ('ATL', 'Atlanta Braves'), ('LAD', 'Los Angeles Dodgers'), ('COL', 'Colorado Rockies'), ('TOR', 'Toronto Blue Jays'), ('HOU', 'Houston Astros'), ('NYM', 'New York Mets'), ('CHC', 'Chicago Cubs'), ('MIA', 'Miami Marlins'), ('CIN', 'Cincinnati Reds'), ('AZ', 'Arizona Diamondbacks'), ('STL', 'St. Louis Cardinals'), ('PIT', 'Pittsburgh Pirates'), ('KC', 'Kansas City Royals'), ('CLE', 'Cleveland Indians'), ('MIL', 'Milwaukee Brewers'), ('SEA', 'Seattle Mariners'), ('LAA', 'Los Angeles Angels'), ('CHW', 'Chicago White Sox'), ('TEX', 'Texas Rangers'), ('SD', 'San Diego Padres'), ('BOS', 'Boston Red Sox'), ('PHI', 'Philadelphia Phillies'), ('NYY', 'New York Yankees'), ('BAL', 'Baltimore Orioles')], default='SD', max_length=254),
        ),
    ]
