# Generated by Django 3.1.7 on 2021-03-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210317_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('CLE', 'Cleveland Indians'), ('NYY', 'New York Yankees'), ('DET', 'Detroit Tigers'), ('KC', 'Kansas City Royals'), ('PHI', 'Philadelphia Phillies'), ('BAL', 'Baltimore Orioles'), ('OAK', 'Oakland Athletics'), ('TEX', 'Texas Rangers'), ('HOU', 'Houston Astros'), ('MIA', 'Miami Marlins'), ('CHW', 'Chicago White Sox'), ('COL', 'Colorado Rockies'), ('BOS', 'Boston Red Sox'), ('TB', 'Tampa Bay Rays'), ('WAS', 'Washington Nationals'), ('NYM', 'New York Mets'), ('STL', 'St. Louis Cardinals'), ('MIL', 'Milwaukee Brewers'), ('PIT', 'Pittsburgh Pirates'), ('AZ', 'Arizona Diamondbacks'), ('CHC', 'Chicago Cubs'), ('LAA', 'Los Angeles Angels'), ('CIN', 'Cincinnati Reds'), ('LAD', 'Los Angeles Dodgers'), ('MIN', 'Minnesota Twins'), ('SEA', 'Seattle Mariners'), ('SD', 'San Diego Padres'), ('SF', 'San Francisco Giants'), ('ATL', 'Atlanta Braves'), ('TOR', 'Toronto Blue Jays')], default='SD', max_length=254),
        ),
    ]
