# Generated by Django 3.1.7 on 2021-03-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210318_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('NYM', 'New York Mets'), ('MIA', 'Miami Marlins'), ('DET', 'Detroit Tigers'), ('SD', 'San Diego Padres'), ('OAK', 'Oakland Athletics'), ('WAS', 'Washington Nationals'), ('NYY', 'New York Yankees'), ('CIN', 'Cincinnati Reds'), ('CHW', 'Chicago White Sox'), ('BOS', 'Boston Red Sox'), ('KC', 'Kansas City Royals'), ('CLE', 'Cleveland Indians'), ('TB', 'Tampa Bay Rays'), ('CHC', 'Chicago Cubs'), ('COL', 'Colorado Rockies'), ('MIL', 'Milwaukee Brewers'), ('LAA', 'Los Angeles Angels'), ('STL', 'St. Louis Cardinals'), ('SEA', 'Seattle Mariners'), ('LAD', 'Los Angeles Dodgers'), ('PHI', 'Philadelphia Phillies'), ('MIN', 'Minnesota Twins'), ('BAL', 'Baltimore Orioles'), ('ATL', 'Atlanta Braves'), ('SF', 'San Francisco Giants'), ('TEX', 'Texas Rangers'), ('TOR', 'Toronto Blue Jays'), ('PIT', 'Pittsburgh Pirates'), ('AZ', 'Arizona Diamondbacks'), ('HOU', 'Houston Astros')], default='SD', max_length=254),
        ),
    ]
