# Generated by Django 3.1.7 on 2021-03-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210318_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('PHI', 'Philadelphia Phillies'), ('SEA', 'Seattle Mariners'), ('SF', 'San Francisco Giants'), ('BAL', 'Baltimore Orioles'), ('CHW', 'Chicago White Sox'), ('DET', 'Detroit Tigers'), ('KC', 'Kansas City Royals'), ('MIL', 'Milwaukee Brewers'), ('NYY', 'New York Yankees'), ('TEX', 'Texas Rangers'), ('SD', 'San Diego Padres'), ('CHC', 'Chicago Cubs'), ('OAK', 'Oakland Athletics'), ('STL', 'St. Louis Cardinals'), ('HOU', 'Houston Astros'), ('PIT', 'Pittsburgh Pirates'), ('CLE', 'Cleveland Indians'), ('ATL', 'Atlanta Braves'), ('CIN', 'Cincinnati Reds'), ('LAA', 'Los Angeles Angels'), ('MIN', 'Minnesota Twins'), ('MIA', 'Miami Marlins'), ('WAS', 'Washington Nationals'), ('NYM', 'New York Mets'), ('LAD', 'Los Angeles Dodgers'), ('TB', 'Tampa Bay Rays'), ('BOS', 'Boston Red Sox'), ('COL', 'Colorado Rockies'), ('TOR', 'Toronto Blue Jays'), ('AZ', 'Arizona Diamondbacks')], default='SD', max_length=254),
        ),
    ]
