# Generated by Django 3.1.7 on 2021-03-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
